version: 1.0.'{build}'

configuration: Release

cache:
  - C:\Users\appveyor\.m2 -> pom.xml

build_script:
  - cmd: java -version
  - cmd: mvn -DskipTests -q package

test_script:
  - cmd: mvn surefire-report:report

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        Get-ChildItem . -Name -Recurse 'TEST-*.xml'  |
        Foreach-Object {
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_))
        }